services:
  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    networks:
      - kafka-network
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: "OUTSIDE://localhost:19092,INSIDE://kafka1:9094"
      KAFKA_LISTENERS: "OUTSIDE://0.0.0.0:19092,INSIDE://kafka1:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INSIDE"
  
  kafka2:
    image: confluentinc/cp-kafka
    container_name: kafka2
    networks:
      - kafka-network
    ports:
      - "19093:19093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: "OUTSIDE://localhost:19093,INSIDE://kafka2:9095"
      KAFKA_LISTENERS: "OUTSIDE://0.0.0.0:19093,INSIDE://kafka2:9095"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INSIDE"
    
  kafka3:
    image: confluentinc/cp-kafka
    container_name: kafka3
    networks:
      - kafka-network
    ports:
      - "19094:19094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: "OUTSIDE://localhost:19094,INSIDE://kafka3:9096"
      KAFKA_LISTENERS: "OUTSIDE://0.0.0.0:19094,INSIDE://kafka3:9096"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INSIDE"

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    networks:
      - kafka-network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka-ui:
    container_name: kafka-ui
    networks:
      - kafka-network
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'

networks:
  kafka-network:
    driver: bridge

volumes:
  kui_config:
    driver: local